### ISSUE TITLE
vrkeyboard with jsartoolkit5

### ISSUE THREAD

**Issue by anakein** [erosmarcon/vr-keyboard#2]
i'm trying add vrkeyboard with marker ar.js, but crash me three always or don't show.

is there compatibility problems?

**Comment by erosmarcon** [comment]
Can you be more specific? 
Do you have any log/error/warn on the browser console?
Some code of what you are trying to do could help.

**Comment by anakein** [comment]
yes.

i am trying show your vrkeyboard when point marker same this. https://github.com/jeromeetienne/AR.js/
in me project all objects work but your vr keyboard is not showing when point marker.  i have not error or warning on console, only don´t show.

**Comment by erosmarcon** [comment]
Maybe due to camera position/settings in relation to object (Keyboard) size/scale?
Did you check it is inside camera's view range and correctly oriented ?
(currently the keyboard has only one visible side)
You could try to move camera away or scale down the keyboard.
Not tried with AR.js, but don't think there should be compatibility problems...

**Comment by erosmarcon** [comment]
closing
